### ISSUE TITLE
数据集和标注问题

### ISSUE THREAD

**Issue by TuoniTuoni** [ShawnBIT/Brain-Midline-Detection#2]
刚接触脑中线项目，请问实验所用数据集可以分享一下吗？还有请问数据是用什么软件标注的，标注时是就标出脑中线的狭长区域就可以吗？谢谢

**Comment by SE-Nickjackson** [comment]
Hi, thanks for your great work. I also want to know how to create a valid dataset. I will appreciate that If you can help me.
